sbatch iqtree_run_70.sh
sbatch iqtree_run_71.sh
sbatch iqtree_run_72.sh
sbatch iqtree_run_73.sh
sbatch iqtree_run_74.sh
sbatch iqtree_run_75.sh
sbatch iqtree_run_76.sh
sbatch iqtree_run_77.sh
sbatch iqtree_run_78.sh
sbatch iqtree_run_79.sh
sbatch iqtree_run_8.sh
sbatch iqtree_run_80.sh
sbatch iqtree_run_81.sh
sbatch iqtree_run_82.sh
sbatch iqtree_run_83.sh
sbatch iqtree_run_84.sh
sbatch iqtree_run_85.sh
sbatch iqtree_run_86.sh
sbatch iqtree_run_87.sh
sbatch iqtree_run_88.sh
sbatch iqtree_run_89.sh
sbatch iqtree_run_9.sh
sbatch iqtree_run_90.sh
sbatch iqtree_run_91.sh
sbatch iqtree_run_92.sh
sbatch iqtree_run_93.sh
sbatch iqtree_run_94.sh
sbatch iqtree_run_95.sh
sbatch iqtree_run_96.sh
sbatch iqtree_run_97.sh
sbatch iqtree_run_98.sh
sbatch iqtree_run_99.sh