sbatch iqtree_run_414.sh
sbatch iqtree_run_415.sh
sbatch iqtree_run_416.sh
sbatch iqtree_run_417.sh
sbatch iqtree_run_418.sh
sbatch iqtree_run_419.sh
sbatch iqtree_run_42.sh
sbatch iqtree_run_420.sh
sbatch iqtree_run_421.sh
sbatch iqtree_run_422.sh
sbatch iqtree_run_423.sh
sbatch iqtree_run_424.sh
sbatch iqtree_run_425.sh
sbatch iqtree_run_426.sh
sbatch iqtree_run_427.sh
sbatch iqtree_run_428.sh
sbatch iqtree_run_429.sh
sbatch iqtree_run_43.sh
sbatch iqtree_run_430.sh
sbatch iqtree_run_431.sh
sbatch iqtree_run_432.sh
sbatch iqtree_run_44.sh
sbatch iqtree_run_45.sh
sbatch iqtree_run_46.sh
sbatch iqtree_run_47.sh
sbatch iqtree_run_48.sh
sbatch iqtree_run_49.sh
sbatch iqtree_run_5.sh
sbatch iqtree_run_50.sh
sbatch iqtree_run_51.sh
sbatch iqtree_run_52.sh
sbatch iqtree_run_53.sh
sbatch iqtree_run_54.sh
sbatch iqtree_run_55.sh
sbatch iqtree_run_56.sh
sbatch iqtree_run_57.sh
sbatch iqtree_run_58.sh
sbatch iqtree_run_59.sh
sbatch iqtree_run_6.sh
sbatch iqtree_run_60.sh
sbatch iqtree_run_61.sh
sbatch iqtree_run_62.sh
sbatch iqtree_run_63.sh
sbatch iqtree_run_64.sh
sbatch iqtree_run_65.sh
sbatch iqtree_run_66.sh
sbatch iqtree_run_67.sh
sbatch iqtree_run_68.sh
sbatch iqtree_run_69.sh
sbatch iqtree_run_7.sh