sbatch iqtree_run_10.sh
sbatch iqtree_run_11.sh
sbatch iqtree_run_12.sh
sbatch iqtree_run_13.sh
sbatch iqtree_run_14.sh
sbatch iqtree_run_15.sh
sbatch iqtree_run_16.sh
sbatch iqtree_run_17.sh
sbatch iqtree_run_18.sh
sbatch iqtree_run_1.sh
sbatch iqtree_run_2.sh
sbatch iqtree_run_3.sh
sbatch iqtree_run_4.sh
sbatch iqtree_run_5.sh
sbatch iqtree_run_6.sh
sbatch iqtree_run_7.sh
sbatch iqtree_run_8.sh
sbatch iqtree_run_9.sh
